name: "Solicitud de Cambio (RFC)"
description: "Proponer un cambio con evaluación de riesgo/impacto y plan de reversa."
title: "[RFC] <título breve del cambio>"
labels: ["rfc", "change-request"]
assignees: []
body:
  - type: textarea
    id: solicitante
    attributes:
      label: Solicitante
      description: Id del solicitante
      placeholder: "1"
    validations:
      required: true

  - type: dropdown
    id: tipo_cambio
    attributes:
      label: Tipo de cambio
      description: Define el nivel de control (estándar va más rápido; emergencia acelera con salvaguardas).
      options: ["Estándar", "Normal", "Emergencia"]
    validations: { required: true }

  - type: dropdown
    id: riesgo
    attributes:
      label: Riesgo
      description: Mide probabilidad/severidad para decidir controles.
      options: ["Bajo", "Medio", "Alto"]
    validations: { required: true }

  - type: textarea
    id: impacto
    attributes:
      label: Impacto
      description: ¿Quién/qué se afecta? ¿Habrá downtime? Sé concreto.
      placeholder: "Afecta API pagos y checkout web. Downtime estimado: 20 min en ventana."
    validations: { required: true }

  - type: textarea
    id: plan
    attributes:
      label: Plan de implementación
      description: Pasos claros y ordenados (numerados).
      placeholder: "1) Respaldar BD\n2) Desplegar versión X\n3) Ejecutar migraciones\n4) Verificar healthchecks"
    validations: { required: true }

  - type: textarea
    id: rollback
    attributes:
      label: Plan de reversa (rollback)
      description: ¿Cómo vuelves atrás si algo falla?
      placeholder: "Revertir a versión anterior y restaurar snapshot BD de las 19:45."
    validations: { required: true }

  - type: textarea
    id: pruebas
    attributes:
      label: Plan de pruebas
      description: Cómo verificas antes y después; criterios de aceptación.
      placeholder: "Smoke tests + flujo de compra; tasa 2xx estable; métricas sin regresiones."
    validations: { required: true }

  - type: input
    id: ventana_inicio
    attributes:
      label: Ventana (inicio)
      description: "Fecha/hora con zona (ISO o claro). Ej.: 2025-11-02 20:00 America/Guayaquil"
      placeholder: "2025-11-02 20:00 America/Guayaquil"
    validations: { required: true }

  - type: input
    id: ventana_fin
    attributes:
      label: Ventana (fin)
      description: "Fecha/hora con zona (ISO o claro). Ej.: 2025-11-02 22:00 America/Guayaquil"
      placeholder: "2025-11-02 22:00 America/Guayaquil"
    validations: { required: true }

  - type: input
    id: aprobadores
    attributes:
      label: Aprobadores requeridos
      description: Correos o @handles (dueño de servicio, seguridad, CAB).
      placeholder: "dueño-servicio@empresa.com; seguridad@empresa.com"
    validations: { required: true }
